acadapp/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('postandcomment.urls')),
    path('', include('login.urls'))
]

login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'login_app'

urlpatterns = [
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
	path('editprofile/', views.profile, name="profile"),
	path('profile/<str:name>', views.profilepage, name="profilepage"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postandcomment/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'postandcomment_app'

urlpatterns = [
    # path('comment/', views.registerPage, name="comment"),
	path('post/<int:post_id>', views.postView, name="post"),  
    path('projectPost/<int:ppost_id>', views.projectPostView, name="projectPost"),  
    path('createPost/<slug:community_name>', views.postCreateView, name="createPost"),
    path('createProject/', views.createProjectPost, name="createProjectPost"),
    path('community/<slug:community_name>', views.communityView, name="community"),
    path('createCommunity/', views.communityCreateView, name='createCommunity'),
    path('community/', views.communityListView, name='com'),
    path('projects/', views.projectListView, name='proj'),
    path('test/', views.testListView, name='test'),
    path('test/<int:test_id>', views.testView, name="tests"),
    path('createTest', views.testCreateView, name="createTest"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from PIL import Image
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    occupation= models.TextField(blank=True)
    age = models.IntegerField(default=18)
    college = models.TextField(blank=True)
    field_of_study = models.TextField(blank=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
    
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     try:
#         instance.profile.save()
#     except ObjectDoesNotExist:
#         Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     try:
#         instance.profile.save()
#     except ObjectDoesNotExist:
#         Profile.objects.create(user=instance)

login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Profile

title= [
    ('student', 'Student'),
    ('faculty', 'Faculty'),
    ('others', 'Others'),
    ]
INTEGER_CHOICES= [tuple([x,x]) for x in range(1,150)]

class CreateUserForm(UserCreationForm):
    occupation= forms.CharField(label='select your professional title', widget=forms.Select(choices=title))
    age = forms.IntegerField(label="select age", widget=forms.Select(choices=INTEGER_CHOICES))
    college = forms.CharField()
    field_of_study = forms.CharField()
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'age', 'occupation', 'college', 'field_of_study', 'username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

login/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required
from .models import *
from .forms import CreateUserForm, UserUpdateForm, ProfileUpdateForm
from postandcomment.models import *
# Create your views here.


def registerPage(request):
	if request.user.is_authenticated:
		return redirect('login_app:register')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				user = form.save()
				user.refresh_from_db()
				# user.userprofile.user = authenticate(username=username, password=password)
				user.save()
				college = form.cleaned_data.get('college')
				if college not in list(Profile.objects.values_list('college', flat=True)):
					newCommunity = Community()
					newCommunity.name = college.replace(" ", "")
					newCommunity.description = f"Incognito Community of {college}"
					newCommunity.save()
					newCommunity.user.add(user)
					newCommunity.save()
				else:
					community = Community.objects.get(name = college.replace(" ", ""))
					community.user.add(user)
				first_name = form.cleaned_data.get('first_name')
				username = form.cleaned_data.get('username')
				password = form.cleaned_data.get('password1')
				user = authenticate(username=username, password=password)
				
				profile = Profile()
				profile.user = user
				profile.college = form.cleaned_data.get('college')
				profile.occupation = form.cleaned_data.get('occupation')
				profile.age = form.cleaned_data.get('age')
				profile.field_of_study = form.cleaned_data.get('field_of_study')
				profile.save()

				login(request, user)
				messages.success(request, 'Account was created for ' + first_name)

				return redirect('login_app:login')
			

		context = {'form':form}
		return render(request, 'login/register.html', context)


def loginPage(request):
	if request.user.is_authenticated:
		return redirect('index')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				
				return redirect('index')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'login/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('login_app:login')
	 
def profile(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			u_form = UserUpdateForm(request.POST, instance=request.user)
			p_form = ProfileUpdateForm(request.POST,
									request.FILES,
									instance=request.user.profile)
			if u_form.is_valid() and p_form.is_valid():
				u_form.save()
				p_form.save()
				messages.success(request, f'Your account has been updated!')
				return redirect('index')

		else:
			u_form = UserUpdateForm(instance=request.user)
			p_form = ProfileUpdateForm(instance=request.user.profile)
			print(u_form, p_form)

		context = {
			'u_form': u_form,
			'p_form': p_form
		}

		return render(request, 'login/profile.html', context)

	else:
		return redirect('index')
	
def profilepage(request,name):

	if request.user.is_authenticated:

		if request.user.username != name:
			value = False
		else:
			value = True

		user = User.objects.get(username = name)
		profile = Profile.objects.get(user = user)
		posts = Post.objects.filter(author = user)
		projectposts = ProjectPost.objects.filter(author = user)
		context = {
			'value':value,
			'user':user,
			'profile':profile,
			'posts':posts,
			'projectposts':projectposts
		}
	return render(request, 'login/profilepage.html', context)
		

login/templates/login/baselog.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
  <style>
      /* body, html {
  height: 100%;
} */

/* The hero image */
.header {
/* Use "linear-gradient" to add a darken background effect to the image (photographer.jpg). This will make the text easier to read */
height: 100vh;
background-position: center;
background-repeat: no-repeat;
background-size: cover;
}
.hero-text {
text-align: center;
position: absolute;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
color: white;
}

a {
color: white;
text-decoration: none;
}

a:hover 
{
color:#00A0C6; 
text-decoration:none; 
cursor:pointer;  
}
  </style>
  <body>

    <!-- <section class="header" style="font-size: 1.2em;">
           <ul class="nav fixed-top my-3 ml-3">
            <li class="nav-item">
              <a class="nav-link active" href="#" style="color: black;">Active</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" style="color: black;">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" style="color: black;">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>

          
            <ul class="nav fixed-top my-3 justify-content-end mr-3">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login_app:logout' %}">Logout</a>
              </li>           
            </ul> -->
            <br><br><br>
          {% block content %}
          
          {% endblock %}
    
    
  </body>
</html>

login/templates/login/indexlog.html
<!doctype html>
<html lang="en">
  <head>
    <title>Dummy</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      <h1>Something</h1>
      <h2>Some changes</h2>
      <h3>Some changes</h3>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

login/templates/login/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: blanchedalmond !important;
			color: black;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: white;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<section class="header" style="font-size: 1.2em;">
		
		 <ul class="nav fixed-top my-3 justify-content-end mr-3">
		   <li class="nav-item">
			 <a class="nav-link" href="{% url 'index' %}">HOME</a>
		   </li>           
		 </ul>
		 <br><br><br><br><br><br><br>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title" style="color: black;">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'login_app:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

login/templates/login/profile.html
{% extends "login/baselog.html" %}
{% load crispy_forms_tags %}
{% block content %}

<style>
    
</style>

<section style="display: flex; justify-content: center; align-items: center;">
    <div class="container">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <div class="content-section">
            <div class="media">
              <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" width="80" height="80">
              <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
              </div>
            </div>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group" style="color: black;">
                    <legend class="border-bottom mb-4">Profile Info</legend>
                    {{ u_form|crispy }}
                    {{ p_form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-success" type="submit">Update Profile</button>
                </div>
            </form>
          </div>
        </div>
        <div class="col-md-2"></div>
      </div>

    </div>
</section>
    
{% endblock content %}

login/templates/login/profilepage.html
<!DOCTYPE html>
<head>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

</head>
<style>
    body{margin-top:20px;}

.profile {
  width: 100%;
  position: relative;
  background: #FFF;
  border: 1px solid #D5D5D5;
  padding-bottom: 5px;
  margin-bottom: 20px;
}

.profile .image {
  display: block;
  position: relative;
  z-index: 1;
  overflow: hidden;
  text-align: center;
  border: 5px solid #FFF;
}

.profile .user {
  position: relative;
  padding: 0px 5px 5px;
}

.profile .user .avatar {
  position: absolute;
  left: 20px;
  top: -85px;
  z-index: 2;
}

.profile .user h2 {
  font-size: 20px;
  
  line-height: 20px;
  display: block;
  float: left;
  margin: 4px 0px 0px 60px;
  font-weight: bold;
}

.profile .user .actions {
  float: right;
}

.profile .user .actions .btn {
  margin-bottom: 0px;
}

.profile .info {
  float: left;
  margin-left: 20px;
}

.img-profile{
    height:200px;
    width:200px;
}

.img-cover{
    width:1200px;
    height:300px;
}

@media (max-width: 768px) {
  .btn-responsive {
    padding:2px 4px;
    font-size:80%;
    line-height: 1;
    border-radius:3px;
  }
}

@media (min-width: 769px) and (max-width: 992px) {
  .btn-responsive {
    padding:4px 9px;
    font-size:90%;
    line-height: 1.2;
  }
}

    body{
      background-color: white;
    }
    .card-tile
{
    display:inline;
}

a:hover {
    text-decoration: none;
    
}

.card {
    transition: all 0.2s ease-in-out;
    -webkit-transform: all 0.2s ease-in-out;
}

.card:hover {
    -webkit-transform: scale(1.1);
}

body{
      background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(https://www.capturehighered.com/wp-content/uploads/2017/11/AdobeStock_76029922-720x360.jpeg);
      background-size: cover;
    }

</style>

<body>
    
    <a href="{% url 'index' %}"><button class="btn btn-dark" style="float: left; border-color: black; margin-left: 10px;">Prev</button></a>
    
    <br><br>
    <div class="container">
        <div class="col" style="border-style: solid; border-width: 1px; border-color: black;">
            <div class="profile clearfix">                            
                <div class="image" >
                    <img src="/media/slant.jpg" class="img-cover">
                </div>                            
                <div class="user clearfix">
                    <div class="avatar">
                        <img src="{{profile.image.url}}" class="img-thumbnail img-profile">
                                          
                    </div>               
                    <br><br><br>  <br><br><br>                         
                    <h2><p><i>{{user.username}}</i></p>  </h2>
                    {% if value %}                           
                    <div class="actions">
                        <div class="btn-group">
                            <a href="{% url 'login_app:profile' %}"><button class="btn btn-default btn-sm tip btn-responsive" title="" data-original-title="Recommend"><span class="glyphicon glyphicon-share-alt glyphicon glyphicon-white"></span>Update My Profile</button></a>
                        </div>
                    </div>       
                    {% endif %}                                                                                         
                </div>                          
                <!--<div class="info" style="display: inline-block;">
                    <p><span class="glyphicon glyphicon-globe"></span> <span class="title">Address:</span>  St. Revutskogo, Kiev, Ukraine</p>                                    
                    <p><span class="glyphicon glyphicon-gift"></span> <span class="title">Date of birth:</span> 14.02.1989</p>                                
                </div>  --> 
                <br><h3 style="margin: 4px 0px 0px 60px;">  DETAILS:</h3><br>
                <table class="center">
                    <tr style="height: 50px;">
                        <td align="center" style="width: 400px;"> 
                            <h5 style="margin: 4px 0px 0px 60px; text-transform: capitalize;">FIRST NAME: <U>      <b> {{user.first_name}}</b> </U></h5>
                        </td>
                        <td align="center" style="width: 400px;"> 
                            <h5 style="margin: 4px 0px 0px 60px; text-transform: capitalize;">LAST NAME: <U>      <b> {{user.last_name}}</b> </U></h5>
                        </td>
                    </tr>
                    <tr style="height: 50px;">
                        <td align="center" style="width: 400px;"> 
                            <h5 style="margin: 4px 0px 0px 60px;">AGE: <U>      <b> {{profile.age}}</b> </U></h5>
                        </td>
                        <td align="center" style="width: 400px;"> 
                            <h5 style="margin: 4px 0px 0px 60px;">INSTITUTE: <U>      <b> {{profile.college}}</b> </U></h5>
                        </td>
                    </tr>
                    <tr style="height: 50px;">
                        <td align="center" style="width: 400px;"> 
                            <h5 style="margin: 4px 0px 0px 60px;">OCCUPATION: <U>      <b> {{profile.occupation}}</b> </U></h5>
                        </td>
                        <td align="center" style="width: 400px;"> 
                            <h5 style="margin: 4px 0px 0px 60px;">FIELD OF STUDY/EXPERTISE: <U>      <b> {{profile.field_of_study}}</b> </U></h5>
                        </td>
                    </tr>
                </table>                   
                <!-- <br><br> -->
               
            </div>
        </div>
<br><br>
        <section style="display: flex; justify-content: center; align-items: center; color: white;">
            <div class="container" >
                <h3> MY POSTS:</h3><br>
                <div class="row">
                    {% for postDetails in posts %}
                        <div class="col-md-4">

                            <a href="{% url 'postandcomment_app:post' postDetails.id %}" style="text-decoration: none;">
                                <div class="card mb-3 align-items-center" style="max-width: 1000px; background-color: white; height: 300px; display: flex; justify-content: center; align-items: center; border-style: solid; border-width: 1px; border-color: black;">
                                    <div class="row no-gutters" style="text-align: center;">
                                    <div class="col">
                                        <div class="card-body">
                                        <h3 class="card-title" >{{postDetails.title}}</h3>
                                        <p class="card-text"> <span><i class="fas fa-thumbs-up"></i></span> {{ postDetails.content }}</p>
                                        <p class="card-text"><small class="text-muted">{{postDetails.date_posted}}</small></p>
                                        </div>
                                    </div>
                                    
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <br>
            <br>
            <br>
        </section>

        <section style="display: flex; justify-content: center; align-items: center; color: white;">
            <div class="container" >
                <h3> MY PROJECTS:</h3><br>
                <div class="row">
                    {% for projectpostDetails in projectposts %}
                        <div class="col-md-4">

                            <a href="{% url 'postandcomment_app:projectPost' projectpostDetails.id %}" style="text-decoration: none;">
                                <div class="card mb-3 align-items-center" style="max-width: 1000px; background-color: white; height: 300px; display: flex; justify-content: center; align-items: center; border-style: solid; border-width: 1px; border-color: black;">
                                    <div class="row no-gutters" style="text-align: center;">
                                    <div class="col">
                                        <div class="card-body">
                                        <h3 class="card-title" >{{projectpostDetails.title}}</h3>
                                        <p class="card-text"> <span><i class="fas fa-thumbs-up"></i></span> {{ projectpostDetails.description }}</p>
                                        <p class="card-text"><small class="text-muted">{{postDetails.date_posted}}</small></p>
                                        </div>
                                    </div>
                                    
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <br>
            <br>
            <br>
        </section>

        </div>
        <br>
        <br>
        <br>
</body> 