acadapp/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('postandcomment.urls')),
    path('', include('login.urls'))
]

login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'login_app'

urlpatterns = [
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
	path('editprofile/', views.profile, name="profile"),
	path('profile/<str:name>', views.profilepage, name="profilepage"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postandcomment/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'postandcomment_app'

urlpatterns = [
    # path('comment/', views.registerPage, name="comment"),
	path('post/<int:post_id>', views.postView, name="post"),  
    path('projectPost/<int:ppost_id>', views.projectPostView, name="projectPost"),  
    path('createPost/<slug:community_name>', views.postCreateView, name="createPost"),
    path('createProject/', views.createProjectPost, name="createProjectPost"),
    path('community/<slug:community_name>', views.communityView, name="community"),
    path('createCommunity/', views.communityCreateView, name='createCommunity'),
    path('community/', views.communityListView, name='com'),
    path('projects/', views.projectListView, name='proj'),
    path('test/', views.testListView, name='test'),
    path('test/<int:test_id>', views.testView, name="tests"),
    path('createTest', views.testCreateView, name="createTest"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acadapp/views.py
from django.shortcuts import render, redirect
from login.models import *


def index(request):

    if request.user.is_authenticated:
        context = {
            'name':request.user.username,
            'college':Profile.objects.get(user=request.user).college.replace(" ", ""),
        }
    else:
        context={}

    return render(request, 'index.html', context)

acadapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AcadHub</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet"> -->
<!-- <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet"> -->
</head>
  <style>
      /* body, html {
  height: 100%;
} */

/* The hero image */
.header {
/* Use "linear-gradient" to add a darken background effect to the image (photographer.jpg). This will make the text easier to read */
background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1950&q=80);
height: 100vh;
background-position: center;
background-repeat: no-repeat;
background-size: cover;
}
.hero-text {
text-align: center;
position: absolute;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
color: white;
}

a {
color: white;
text-decoration: none;
}

a:hover 
{
color:#00A0C6; 
text-decoration:none; 
cursor:pointer;  
}

td {
  padding-left: 50px;
  padding-right: 50px;
  background-color: rgb(15, 14, 14);
  height: 300px;
  border: 20px solid rgb(255, 255, 255);
  text-align: center;
}

td:first-child {
  padding-left: 50px;
}

td:last-child {
  padding-right: 50px;
}


table {
  width: calc(100% + 30px);
  table-layout: fixed;
  border-spacing: 50px 0px;
  margin: 0px -15px;
}

.table-container {
  overflow: hidden;
  width: 90%;
  margin: 0 auto;
}
  </style>
  <body>

    <section class="header" style="font-size: 1.2em;">
          <!--<ul class="nav fixed-top my-3 ml-3">
            <li class="nav-item">
              <a class="nav-link active" href="#">Active</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>--> 

          {% if not request.user.is_authenticated %}
              <ul class="nav justify-content-end mr-3">
                <li class="nav-item mt-3">
                  <a class="nav-link active " href="{% url 'login_app:login' %}">Login</a>
                </li>
                <li class="nav-item mt-3">
                  <a class="nav-link" href="{% url 'login_app:register' %}">Sign Up</a>
                </li>
              
              </ul>
          {% else %}
            <ul class="nav justify-content-end mr-3">
              <li class="nav-item mt-3">
                <a class="nav-link" href="{% url 'login_app:logout' %}">Logout</a>
              </li>
              <li class="nav-item mt-3">
                <a class="nav-link active" href="{% url 'login_app:profilepage' name %}">Profile</a>
              </li>            
            </ul>
            {% endif %} 
    </section>


    <br>
    <br>
    <br>
    <br>

    <section>
      <div class="hero-text">
        <h1 class="display-1">AcadHub</h1>
        <h3 class="display-4">Some Random Text</h3>
        <a href="{% url 'postandcomment_app:com' %}"><button class="btn btn-outline-danger">Explore Communities</button></a>
      </div>
    </section>

    <section style="display: flex; justify-content: center; align-items: center;">
      <div class="container" align="center">
        <h2>Community</h2>
        <br>
        <div class="row">
          <a href="/community/Projects"><div class="col com bg-danger m-2" style="height: 50vh; width: 28vw;">Project</div></a>
          <a href=""><div class="col com bg-info m-2" style="height: 50vh; width: 28vw;">Guidance</div></a>
          <a href=""><div class="col com bg-success m-2" style="height: 50vh; width: 28vw;">Innovation</div></a>
        </div>
        <div class="row">
          <a href=""><div class="col com bg-warning m-2" style="height: 50vh; width: 28vw;">Test</div></a>
          {% if not request.user.is_authenticated %}
          <a href="{% url 'login_app:login' %}"><div class="col com bg-primary m-2" style="height: 50vh; width: 28vw;">College Community</div></a>
          {% else %}
          <a href="{% url 'postandcomment_app:community' college %}"><div class="col com bg-primary m-2" style="height: 50vh; width: 28vw;">College Community</div></a>
          {% endif %}
          <a href=""><div class="col com bg-dark m-2" style="height: 50vh;  width: 28vw;">Instructor Community</div></a>  
        </div>
      </div>

      <style>
        .com{
          display: flex; justify-content: center; align-items: center;
          font-size: 2em;
          color: white;
        }
      </style>
      
    
    
  </section>
  {% if request.user.is_authenticated %}
  <br>
  <div align="center">
    <a href="{% url 'postandcomment_app:createCommunity' %}"><button class="btn btn-outline-danger" align="center"> Create a Community</button></a>
  </div>
  <br>
  <br>
    {% endif %} 

    
  
    
    
  </body>
</html>

acadapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AcadHub</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet"> -->
<!-- <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet"> -->
</head>
  <style>
      /* body, html {
  height: 100%;
} */

/* The hero image */
.header {
/* Use "linear-gradient" to add a darken background effect to the image (photographer.jpg). This will make the text easier to read */
background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1950&q=80);
height: 100vh;
background-position: center;
background-repeat: no-repeat;
background-size: cover;
}
.hero-text {
text-align: center;
position: absolute;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
color: white;
}

a {
color: white;
text-decoration: none;
}

a:hover 
{
color:#00A0C6; 
text-decoration:none; 
cursor:pointer;  
}

td {
  padding-left: 50px;
  padding-right: 50px;
  background-color: rgb(15, 14, 14);
  height: 300px;
  border: 20px solid rgb(255, 255, 255);
  text-align: center;
}

td:first-child {
  padding-left: 50px;
}

td:last-child {
  padding-right: 50px;
}


table {
  width: calc(100% + 30px);
  table-layout: fixed;
  border-spacing: 50px 0px;
  margin: 0px -15px;
}

.table-container {
  overflow: hidden;
  width: 90%;
  margin: 0 auto;
}
  </style>
  <body>

    <section class="header" style="font-size: 1.2em;">
          <!--<ul class="nav fixed-top my-3 ml-3">
            <li class="nav-item">
              <a class="nav-link active" href="#">Active</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>--> 

          {% if not request.user.is_authenticated %}
              <ul class="nav justify-content-end mr-3">
                <li class="nav-item mt-3">
                  <a class="nav-link active " href="{% url 'login_app:login' %}">Login</a>
                </li>
                <li class="nav-item mt-3">
                  <a class="nav-link" href="{% url 'login_app:register' %}">Sign Up</a>
                </li>
              
              </ul>
          {% else %}
            <ul class="nav justify-content-end mr-3">
              <li class="nav-item mt-3">
                <a class="nav-link" href="{% url 'login_app:logout' %}">Logout</a>
              </li>
              <li class="nav-item mt-3">
                <a class="nav-link active" href="{% url 'login_app:profilepage' name %}">Profile</a>
              </li>            
            </ul>
            {% endif %} 
    </section>


    <br>
    <br>
    <br>
    <br>

    <section>
      <div class="hero-text">
        <h1 class="display-1">AcadHub</h1>
        <h3 class="display-6">Together we BUILD, Together we GROW</h3>
        <a href="{% url 'postandcomment_app:com' %}"><button class="btn btn-danger">Explore Communities</button></a>
      </div>
    </section>

    <section style="display: flex; justify-content: center; align-items: center;">
      <div class="container" align="center">
        <h2 class="display-1">Community</h2>
        <br>
        <div class="row">
          <a href="{% url 'postandcomment_app:proj' %}"><div class="col com bg-danger m-2" style="height: 50vh; width: 28vw;">Project</div></a>
          {% if not request.user.is_authenticated %}
          <a href="{% url 'login_app:login' %}"><div class="col com bg-primary m-2" style="height: 50vh; width: 28vw;">College Community</div></a>
          {% else %}
          <a href="{% url 'postandcomment_app:community' college %}"><div class="col com bg-primary m-2" style="height: 50vh; width: 28vw;">College Community</div></a>
          {% endif %}
          <a href=""><div class="col com bg-dark m-2" style="height: 50vh;  width: 28vw;">Instructor Community</div></a>
        </div>
        <div class="row">
          <a href=""><div class="col com bg-info m-2" style="height: 50vh; width: 28vw;">Guidance</div></a>
          <a href=""><div class="col com bg-success m-2" style="height: 50vh; width: 28vw;">Innovation</div></a>
          <a href="{% url 'postandcomment_app:test' %}"><div class="col com bg-warning m-2" style="height: 50vh; width: 28vw;">Test</div></a>
        </div>
      </div>

      <style>
        .com{
          display: flex; justify-content: center; align-items: center;
          font-size: 2em;
          color: white;
          /* -webkit-transform: scale(1.2); */
        }
        /* table a:hover{  } */
      </style>
      
    
    
  </section>
  {% if request.user.is_authenticated %}
  <br>
  <div align="center">
    <a href="{% url 'postandcomment_app:createCommunity' %}"><button class="btn btn-danger" align="center"> Create a Community</button></a>
  </div>
  <br>
  <br>
    {% endif %} 

    
  
    
    
  </body>
</html>