acadapp/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('postandcomment.urls')),
    path('', include('login.urls'))
]

login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'login_app'

urlpatterns = [
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
	path('editprofile/', views.profile, name="profile"),
	path('profile/<str:name>', views.profilepage, name="profilepage"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postandcomment/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'postandcomment_app'

urlpatterns = [
    # path('comment/', views.registerPage, name="comment"),
	path('post/<int:post_id>', views.postView, name="post"),  
    path('projectPost/<int:ppost_id>', views.projectPostView, name="projectPost"),  
    path('createPost/<slug:community_name>', views.postCreateView, name="createPost"),
    path('createProject/', views.createProjectPost, name="createProjectPost"),
    path('community/<slug:community_name>', views.communityView, name="community"),
    path('createCommunity/', views.communityCreateView, name='createCommunity'),
    path('community/', views.communityListView, name='com'),
    path('projects/', views.projectListView, name='proj'),
    path('test/', views.testListView, name='test'),
    path('test/<int:test_id>', views.testView, name="tests"),
    path('createTest', views.testCreateView, name="createTest"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postandcomment/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse

# Create your models here.

class Community(models.Model):
    name = models.CharField(max_length=200, default='SomeName')
    description = models.CharField(max_length=400, blank=True)
    user = models.ManyToManyField(User)
    
class Post(models.Model):
    content = models.TextField(default="testContent")
    title = models.TextField(default="testPost")
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='post_pics', blank = True)
    upvote = models.PositiveIntegerField(default=0)
    downvote = models.PositiveIntegerField(default=0)
    category = models.CharField(default='global', max_length=200)
    link = models.URLField(blank = True)
    community = models.ForeignKey(Community, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.author.username} Post- {self.title}'

    def save(self, *args, **kwargs): 
        super().save(*args, **kwargs) 
        img = Image.open(self.image.path) 
        if img.height > 400 or img.width > 400: 
            output_size = (300, 300) 
            img.thumbnail(output_size) 
            img.save(self.image.path)
    

class Comment(models.Model): 
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name ='comments') 
    user = models.ForeignKey(User, on_delete = models.CASCADE) 
    content = models.TextField() 
    date = models.DateTimeField(default=timezone.now)
    upvotes = models.PositiveIntegerField(default=0)

class ProjectPost(models.Model):
    title = models.TextField(default="testPost")
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_name')
    contributors = models.ManyToManyField(User)
    requirements = models.TextField(default='Dedication')
    description = models.TextField(default='Important Project')
    domain = models.TextField(default='general')
    deadline = models.DateTimeField(default=timezone.now)
    image = models.ImageField(default='default.jpg', upload_to='post_pics', blank = True)
    link = models.URLField(blank = True)

    def __str__(self):
        return f'{self.author.username} Post- {self.title}'

    def save(self, *args, **kwargs): 
        super().save(*args, **kwargs) 
        img = Image.open(self.image.path) 
        if img.height > 400 or img.width > 400: 
            output_size = (300, 300) 
            img.thumbnail(output_size) 
            img.save(self.image.path)

class PComment(models.Model): 
    ppost = models.ForeignKey(ProjectPost, on_delete = models.CASCADE, related_name ='comments') 
    user = models.ForeignKey(User, on_delete = models.CASCADE) 
    content = models.TextField() 
    date = models.DateTimeField(default=timezone.now)

class Test(models.Model):
    user = models.ManyToManyField(User)
    testpost = models.ForeignKey(Post, on_delete = models.CASCADE)

postandcomment/forms.py
from django import forms 
from .models import *

class ProjectPostForm(forms.ModelForm):
    class Meta:
        model = ProjectPost
        fields = ['title','description','requirements','domain','deadline','image','link']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','category','image', 'link']

class CommentForm(forms.ModelForm):
    content = forms.CharField(label ="", widget = forms.Textarea( 
    attrs ={ 
        'class':'form-control', 
        'placeholder':'Comment here !', 
        'rows':4, 
        'cols':50
    }))
    class Meta: 
        model = Comment 
        fields =['content']

class PCommentForm(forms.ModelForm):
    content = forms.CharField(label ="", widget = forms.Textarea( 
    attrs ={ 
        'class':'form-control', 
        'placeholder':'Comment here !', 
        'rows':4, 
        'cols':50
    }))
    class Meta: 
        model = PComment 
        fields =['content']

class CommunityForm(forms.ModelForm):
    class Meta:
        model = Community
        fields = ['name', 'description']

postandcomment/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from login.models import *
from . import models
# Create your views here.

# def postView(request):
#   return render(request, 'index')

def postView(request, post_id): 
  currentPost = Post.objects.get(id=post_id)
  currentPostComments = Comment.objects.filter(post=currentPost).order_by("-post_id")
  currentUserProfile = Profile.objects.get(user=request.user)
  college = currentUserProfile.college.replace(" ", "")
  
  if request.method == 'POST': 
    cf = CommentForm(request.POST or None) 
    if cf.is_valid(): 
      content = request.POST.get('content') 
      if currentPost.community.name == college:
        comment = Comment.objects.create(post = currentPost, user = User.objects.get(username='anonymous'), content = content) 
      else:
        comment = Comment.objects.create(post = currentPost, user = request.user, content = content) 
      comment.save() 
      return redirect('postandcomment_app:post', post_id = post_id) 
  else: 
    cf = CommentForm() 

  context ={ 
    'postDetails': currentPost,
    'comments': currentPostComments,
    'comment_form':cf, 
    } 
  return render(request, 'post.html', context)

def postCreateView(request, community_name):
  currentCommunity = Community.objects.get(name=community_name)
  currentUserProfile = Profile.objects.get(user=request.user)
  college = currentUserProfile.college.replace(" ", "")
  if request.method == 'POST': 
    pf = PostForm(request.POST or None, request.FILES or None) 
    if pf.is_valid():
      if request.FILES.get('image'):
        newPost = Post(image=request.FILES['image'])
      else:
        newPost = Post()
      if college==community_name:
        newPost.author = User.objects.get(username='anonymous')
      else:
        newPost.author = request.user
      newPost.community = currentCommunity
      newPost.content = pf.cleaned_data['content']
      newPost.category = pf.cleaned_data['category']
      newPost.link = pf.cleaned_data['link']
      newPost.title = pf.cleaned_data['title']
      # newPost.image = pf.cleaned_data.get('image', None)
      newPost.save()
      return redirect('postandcomment_app:post', post_id = newPost.id) 
  else: 
    pf = PostForm() 
    
  context = {
    'post_form':pf, 
  } 
  return render(request, 'newPost.html', context) 

def communityView(request, community_name):
  currentCommunity = Community.objects.get(name=community_name) 
  posts = Post.objects.filter(community = currentCommunity)

  context = {
    'community':currentCommunity,
    'posts':posts,
  }

  return render(request, 'post_list.html', context)

def communityCreateView(request):
  comf = CommunityForm(request.POST)
  if request.method == 'POST':
    if comf.is_valid():
      newCom = Community()
      newCom.name = comf.cleaned_data['name']
      newCom.description = comf.cleaned_data['description']
      newCom.save()
      return redirect('index')

  context = {
    'community_form': comf,
  }
  return render(request, 'newCommunity.html', context)

def communityListView(request):
  currentCommunity = Community.objects.all()

  context = {
    'community': currentCommunity, 
  }
  return render(request, 'com_list.html', context)

def projectListView(request):
  projects = ProjectPost.objects.all()
  context = {
    'posts': projects,
  }
  return render(request, 'projectPostList.html', context)

def createProjectPost(request):
  if request.method == 'POST': 
    ppf = ProjectPostForm(request.POST or None, request.FILES or None) 
    if ppf.is_valid():
      if request.FILES.get('image'):
        newPost = ProjectPost(image=request.FILES['image'])
      else:
        newPost = ProjectPost()
      newPost.author = request.user
      newPost.description = ppf.cleaned_data['description']
      newPost.requirements = ppf.cleaned_data['requirements']
      newPost.domain = ppf.cleaned_data['domain']
      newPost.deadline = ppf.cleaned_data['deadline']
      newPost.link = ppf.cleaned_data['link']
      newPost.title = ppf.cleaned_data['title']
      # newPost.image = pf.cleaned_data.get('image', None)
      newPost.save()
      newPost.contributors.add(request.user)
      newPost.save()
      return redirect('postandcomment_app:projectPost', ppost_id = newPost.id) 
  else: 
    ppf = ProjectPostForm() 
    
  context = {
    'post_form':ppf, 
  } 
  return render(request, 'newPost.html', context) 

def projectPostView(request, ppost_id):
  currentPost = ProjectPost.objects.get(id=ppost_id)
  contributors = currentPost.contributors.all()
  currentPostComments = PComment.objects.filter(ppost=currentPost).order_by("-ppost_id")
  currentUserProfile = Profile.objects.get(user=request.user)
  college = currentUserProfile.college.replace(" ", "")
  
  if request.method == 'POST': 
    if 'comment' in request.POST:
      pcf = PCommentForm(request.POST or None) 
      if pcf.is_valid(): 
        content = request.POST.get('content')
        comment = PComment.objects.create(ppost = currentPost, user = request.user, content = content) 
        comment.save() 
        return redirect('postandcomment_app:projectPost', ppost_id = ppost_id) 
    else:
      currentPost.contributors.add(request.user)
      currentPost.save()
      pcf = PCommentForm() 
      contributors = currentPost.contributors.all()
  else: 
    pcf = PCommentForm() 

  if request.user in list(contributors):
    context ={ 
    'formPresent': 'yes',
    'postDetails': currentPost,
    'comments': currentPostComments,
    'contributors': contributors,
    'comment_form':pcf, 
    } 
  else:
    context ={ 
    'formPresent': 'no',
    'postDetails': currentPost,
    'contributors': contributors,
    'comments': currentPostComments,
    } 
  
  return render(request, 'projectPost.html', context)

def testListView(request):
  tests = Test.objects.all()
  posttest = [x.testpost for x in tests]
  context = {
    'ptest':posttest,  
  }
  return render(request, 'test_list.html', context)

def testView(request, test_id):
  ptest = Post.objects.get(id=test_id)
  currentPostComments = Comment.objects.filter(post=ptest)
  currentUserProfile = Profile.objects.get(user=request.user)
  college = currentUserProfile.college.replace(" ", "")
  
  if request.method == 'POST': 
    tcf = CommentForm(request.POST or None) 
    if tcf.is_valid(): 
      content = request.POST.get('content') 
      comment = Comment.objects.create(post = ptest, user = request.user, content = content) 
      comment.save() 
      return redirect('postandcomment_app:tests', post_id = test_id) 
  else: 
    tcf = CommentForm() 

  context ={ 
    'postDetails': ptest,
    'comments': currentPostComments,
    'comment_form':tcf, 
    } 
  return render(request, 'test.html', context)

def testCreateView(request):
  currentUserProfile = Profile.objects.get(user=request.user)
  if request.method == 'POST': 
    tpf = PostForm(request.POST or None, request.FILES or None) 
    if tpf.is_valid():
      if request.FILES.get('image'):
        newtest = Post(image=request.FILES['image'])
      else:
        newtest = Post()
      newtest.author = request.user
      newtest.community = Community.objects.get(name='test')
      newtest.content = tpf.cleaned_data['content']
      newtest.category = tpf.cleaned_data['category']
      newtest.link = tpf.cleaned_data['link']
      newtest.title = tpf.cleaned_data['title']
      # newPost.image = pf.cleaned_data.get('image', None)
      newtest.save()
      return redirect('postandcomment_app:tests', test_id = newtest.id) 
  else: 
    tpf = PostForm() 
    
  context = {
    'post_form':tpf, 
  } 
  return render(request, 'newtest.html', context)

postandcomment/templates/com_list.html
<!doctype html>
<html lang="en">
  <head>
    <title>AcadHub</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <style>
    body{
      background-color: blanchedalmond;
    }
    .card-tile
{
    display:inline;
}

a:hover {
    text-decoration: none;
    
}

.card {
    transition: all 0.2s ease-in-out;
    -webkit-transform: all 0.2s ease-in-out;
}

.card:hover {
    -webkit-transform: scale(1.1);
}
body{
      background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(https://thumbs.dreamstime.com/z/modern-multicultural-society-concept-crowd-people-group-different-community-isolated-white-background-139167994.jpg);
      background-size: cover;
    }
  </style>
  <body>
    <div class="row">
      <div class="col-4">
        <a href="{% url 'index' %}"><button class="btn btn-dark ml-4 mt-4" style="float: left;">Prev</button></a>
      </div>
      <div class="col-4 mt-1">
        <h1 style="font-size: 4em; color: white;">Communities</h1>
      </div>
      <div class="col-4">
        {% if request.user.is_authenticated %}
        <a href="{% url 'postandcomment_app:createCommunity' %}"><button class="btn btn-primary mt-4 mr-4" style="float: right;"> Create a Community</button></a>
        {% endif %}
      </div>
    </div>
    
    <!-- <br><br> -->
    <br>
      
      <section style="display: flex; justify-content: center; align-items: center;">
        <div class="container">
            <div class="row">
            {% for com in community %}
                {% if com.name != 'Anonymous' %}
                <div class="col-md-4">
                    <a href="{% url 'postandcomment_app:community' com.name %}" style="text-decoration: none;">
                        <div class="card mb-3 align-items-center" style="background-color:white; height: 300px; display: flex; justify-content: center; align-items: center; border-style: solid; border-width: 1px;">
                            <div class="row no-gutters">
                                <div class="col">
                                    <div class="card-body">
                                        <h3 class="card-title">{{com.name}}</h3>
                                        <p class="card-text"> <span><i class="fas fa-thumbs-up"></i></span> {{ com.description }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endif %}
            {% endfor %}
            </div>
        </div>
        </section>
        
      </section>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

postandcomment/templates/newPost.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <style>
    body{
      background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(https://images.pexels.com/photos/2004161/pexels-photo-2004161.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);
      background-size: cover;
      color: white;
    }
  </style>
  <body>
    <h1 class='display-2' align='center'>Create a Post/Project</h1>
    <br>

    <section style="display: flex; justify-content: center; align-items: center;">
      <form enctype="multipart/form-data" method="POST"> 
        {% csrf_token %} 
        <div class="container">
          <div class="col">
            <div class="row-1"></div>
            <div class="row-8"></div>
            <div class="row-1"></div>
          </div>
          <table>{{post_form.as_table}}</table>
        </div>
        <br>
        <div align="center">
          <input type="submit" name="comment" class="btn btn-warning" >
        </div>
        <br><br>
    
      </form> 
    </section>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

postandcomment/templates/post.html
{% load crispy_forms_tags %} 
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <style>
    body{
      background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(https://thumbs.dreamstime.com/z/modern-multicultural-society-concept-crowd-people-group-different-community-isolated-white-background-139167994.jpg);
      background-size: cover;
      color: white;
    }
  </style>
  <body>

    <a href="{% url 'postandcomment_app:com' %}"><button class="btn btn-danger mt-4 ml-5" style="float: left;  border-color: black;">Prev</button></a>
    <br><br>
    <section style="display: flex; justify-content: center; align-items: center;">
      <div class="container">
          <div class="row">
            <div class="col-2"></div>
            <div class="col-8 p-3" style="border: black 1px solid;">
              <h1 style="font-size: 4em;">{{ postDetails.title }}</h1>
              
              
              <h5 class="text" style="color: white;"><small>Published on {{ postDetails.date_posted|date:"F d, Y" }}</small> </h5>
              
              <h5><small class="text" style="color: white;">Author: <a href="{% url 'login_app:profilepage' postDetails.author.username %}">{{postDetails.author.username}}</a></small></h5>
              <legend class="border-bottom mb-4"></legend>
              {% if postDetails.image.url != '/media/default.jpg' %}
                
                <img src="{{postDetails.image.url}}" class="imgpost">
              {% endif %}
                
          {% if postDetails.link != "" %}
              <p class="article-content">
              <a href="{{ postDetails.link }}" target="_blank">{{ postDetails.link }}</a>
              </p>
          {% endif %}
          <p class="article-content">{{ postDetails.content }}</p>  
          <form method="POST">
              {% csrf_token %}
                {{comment_form.as_p}}
                <input type="submit" name="comment" class="btn btn-warning">
              
            </form>  
          <div class="main-comment-section">
              {{comments.count}} Comment{{comments|pluralize}}
            </div>
            
            {% for comment in comments %}
              <blockquote class="blockquote p-2" style="border: black 1px solid;">
                <p>{{ comment.content}}</p>
                <footer class="blockquote-footer" style="color: white;">
                  By <cite><a href="{% url 'login_app:profilepage' comment.user %}">{{comment.user|capfirst}}</a>
                </footer>
              </blockquote>
            {% endfor %}
            </div>
            <div class="col-2"></div>
          </div>
          
      </div>
    </section>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

postandcomment/templates/post_list.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <style>
    body{
      background-color: blanchedalmond;
    
      background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(https://thumbs.dreamstime.com/z/modern-multicultural-society-concept-crowd-people-group-different-community-isolated-white-background-139167994.jpg);
      background-size: cover;
    }
    .card-tile
{
    display:inline;
}

a:hover {
    text-decoration: none;
    
}

.card {
    transition: all 0.2s ease-in-out;
    -webkit-transform: all 0.2s ease-in-out;
}

.card:hover {
    -webkit-transform: scale(1.1);
}
  </style>
  <body>
      
      
    <section style="display: flex; justify-content: center; align-items: center;">
        <div class="container">
          <div class="row">
            <div class="col-4">
              <a href="{% url 'postandcomment_app:com' %}"><button class="btn btn-dark mr-5 mt-4" style="float: left;">Prev</button></a>
            </div>
            <div class="col-4">
              <h1 align='center' style="display: inline-block; font-size: 4em; color: white;">{{community.name}}</h1>
            </div>
            <div class="col-4">
              {% if request.user.is_authenticated %}
            <a href="{% url 'postandcomment_app:createPost' community.name %}"><button class="btn btn-primary mr-5 mt-4" style="float: right;">Create Post</button></a>
            {% endif %}
            </div>
          </div>
            
            
            
            <legend class="border-bottom mb-4"></legend>
            <br>
            
            <div class="row">
              {% for postDetails in posts %}
              <div class="col-md-4">
  
                {% if request.user.is_authenticated %}
                  <a href="{% url 'postandcomment_app:post' postDetails.id %}" style="text-decoration: none;">
                      <div class="card mb-3 align-items-center" style="max-width: 1000px; height: 300px; display: flex; justify-content: center; align-items: center;">
                          <div class="row no-gutters">
                          <div class="col">
                              <div class="card-body">
                              <h5 class="card-title">{{postDetails.title}}</h5>
                              <p class="card-text"> <span><i class="fas fa-thumbs-up"></i></span> {{ postDetails.content }}</p>
                              <p class="card-text"><small class="text-muted">{{postDetails.date_posted}}</small></p>
                              <p class="card-text"><small class="text-muted">Post by {{postDetails.author}}</small></p>
                              </div>
                          </div>
                          </div>
                      </div>
                  </a>
                {% else %}

                  <div class="card mb-3 align-items-center" style="max-width: 1000px; height: 300px; display: flex; justify-content: center; align-items: center;">
                    <div class="row no-gutters">
                    <div class="col">
                        <div class="card-body">
                        <h5 class="card-title">{{postDetails.title}}</h5>
                        <p class="card-text"> <span><i class="fas fa-thumbs-up"></i></span> {{ postDetails.content }}</p>
                        <p class="card-text"><small class="text-muted">{{postDetails.date_posted}}</small></p>
                        <p class="card-text"><small class="text-muted">Post by {{postDetails.author}}</small></p>
                        </div>
                    </div>
                    </div>
                </div> 
                {% endif %}
              </div>
              {% endfor %}
            </div>
        </div>
    </section>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>